import time
from langchain.vectorstores import Pinecone
import pinecone
from langchain.vectorstores import chroma
from langchain import OpenAI
from langchain.chat_models import ChatOpenAI
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.chains.summarize import load_summarize_chain
from langchain.chains import create_extraction_chain
import os
# Vector Store and retrievals
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.chains import RetrievalQA
from langchain.vectorstores import chroma
from langchain.chains import create_extraction_chain, create_extraction_chain_pydantic
from langchain.prompts.chat import (
        ChatPromptTemplate,
        SystemMessagePromptTemplate,
        HumanMessagePromptTemplate
    )

st=str("""LOGIN Now Reading: DATA SCIENCE IS CHANGING THE GAME FOR THE FINTECH SECTOR EXPERT OPINION DATA SCIENCE IS CHANGING THE GAME FOR THE FINTECH SECTOR With the increasing volume of data generated through financial transactions, it is crucial for financial institutions to extract meaningful insights from it to drive decision-making, bolster innovation and gain a competitive edge. Ritesh Mohan Srivastava1 Stories Thursday August 24, 2023, 4 min Read As the world of fintech grows rapidly, the amount of data that has been generated on a daily basis is also increasing exponentially. Data has emerged as one of the prestigious possessions for both businesses and consumers. According to multiple reports, this data is estimated to be 2.5 quintillion bytes, extracted from various sources such as financial transactions, market data, and customer information.  And this is only increasing with every passing second. It is no surprise to anyone that traditional data processing methods are not fully equipped to handle such a massive dataset, often leading to inaccurate or incomplete insights and misleading conclusions.  With the increasing volume of data generated through financial transactions, it is crucial for financial institutions to extract meaningful insights from it to drive decision-making, bolster innovation and gain a competitive edge. This is where data science comes into the picture, playing a vital role in transforming and harnessing raw unstructured data into meaningful insights so that fintech companies can benefit from it.   With the potential to generate up to $1 trillion annual value as per a report by McKinsey & Company, data science has been a game-changer for the fintech industry. It has completely revolutionised the way financial data has been analysed, resulting in predicting market trends, mitigating risk and preventing fraudulent activities, and providing innovative products and services to consumers.   Unleashing the power of data science Data science combines the fields of statistics, mathematics, data analysis, and machine learning to unlock valuable insights from the enormous amounts of financial data generated by the fintech sector. Data scientists collect, clean, organise, and analyse data from various sources to uncover patterns and correlations. They employ advanced machine learning algorithms to build predictive models and communicate their findings through data visualisation.  The primary reason why data science is playing a pivotal role in the fintech industry lies in its ability to uncover patterns and trends within the data. Through the analysis of extensive datasets, data scientists can make more accurate predictions and forecasts, which empowers them to make more informed decisions regarding risk management, investment strategies, and customer behavior.  For instance, by scrutinising customer transaction data, a fintech company can identify patterns indicative of potential security threats and can proactively take measures to prevent them. Data science: Transforming the Indian fintech industry Before the widespread acceptance of the power of data science, the fintech industry faced a number of significant challenges, with fraud and cybersecurity threats being top concerns. With the rise of online banking and digital transactions, there was an increasing need for robust security measures to protect sensitive financial information.  Additionally, the lack of advanced analytics tools made it difficult for the fast-growing fintech industry to understand customer behavior and preferences at a granular level. This resulted in a one-size-fits-all approach, which did not meet the evolving needs of customers.  However, advanced data analytics techniques that are fast gaining acceptance, such as machine learning and artificial intelligence algorithms, can analyse large volumes of transaction data in real-time and identify patterns and anomalies that indicate fraudulent activities. This has helped fintech companies enhance security measures and protect customers from financial fraud. By leveraging the benefits of data science tools, now fintech companies can gain insights into individual preferences, behaviors, and needs. This facilitates the customisation of products and services to meet each customer's specific requirements. Additionally, data science helps in better underwriting that enables fintechs to offer credit to underserved and unbanked merchants and consumers across the country.  Fintech industry also had limitations in terms of scalability and efficiency. Manual processes and legacy systems often resulted in slow and cumbersome operations, leading to delays in customer service and transaction processing. This inefficiency, in turn, hindered the growth potential of fintech companies and made it difficult for them to compete with larger financial institutions.  However, machine learning algorithms have helped in automating repetitive processes, reducing processing time, and improving overall efficiency. In addition to this, technologies like blockchain are playing a significant role in mitigating these problems.  In the fintech industry, data science is not just a buzzword but a catalyst for transformative change. And to foster an environment conducive to data science, it is imperative that the companies understand the power of data science and leverage the same to further accelerate the growth of individual businesses as well as the industry at large.  Ritesh Srivastava is the Chief Data Scientist at fintech company BharatPe (Disclaimer: The views and opinions expressed in this article are those of the author and do not necessarily reflect the views of YourStory.) DATA SCIENCE FINTECH DIGITAL TRANSFORMATION RECOMMENDED STORIES FOR YOU SOCIALSTORY IMPACT Doubling returns on crops, this engineer's NGO is making farming profitable in Bihar August 26, 2023, 6 min Read INTERVIEW Setting the record straight: How Mamaearth dealt with its IPO controversy August 25, 2023, 4 min Read TECHNOLOGY 5 ChatGPT plugins that can help improve business productivity August 25, 2023, 3 min Read AI GEN Google's Dark Web Report Launches in India: A Simple Guide August 24, 2023, 3 min Read AI GEN Elon Musk’s 5 Golden Keys to Entrepreneurial Success August 24, 2023, 2 min Read AI GEN Overcoming Fear: The Power of Living in the Present August 23, 2023, 2 min Read OTHERS 3 strategies for generating multiple streams of significant income August 22, 2023, 3 min Read AI GEN Asian Paints: India’s Biggest Data Science Company that Sells Paint August 17, 2023, 2 min Read STORIES & MEDIA Brands of India SMB Story YS Gulf HerStory SocialStory Enterprise Story The Decrypting Story The Captable YS Life YS Hindi YS Tamil Creators Story AutoStory EVENTS All Events TechSparks '23 VIDEOS YourStory TV LEARN YS University MORE Companies YS Club Partner with Us MyStory YS Research Covid Tributes ABOUT US Advertise with us Meet the team Careers Contact Us Privacy Policy STAY UPDATED Didn't find what you were looking for? Search for what you want, categories, tags, keywords, authors, events, anything under YourStory. STAY CONNECTED Download Yourstory App : Copyright @ YourStory 2023 ENGLISH

Read more at: https://yourstory.com/2023/08/data-science-is-changing-game-for-fintech""")




def summarize(text):
    llm = OpenAI(temperature=0.5,openai_api_key="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")
    from langchain.text_splitter import CharacterTextSplitter
    text_splitter = CharacterTextSplitter()
    from langchain.chains.mapreduce import MapReduceChain
    texts = text_splitter.split_text(text)
    from langchain.docstore.document import Document
    docs = [Document(page_content=t) for t in texts[:3]]

    from langchain.chains.summarize import load_summarize_chain

    template=f"""
               provide an elaborated  and well defined summary of the given text
                """
    system_message_prompt_map = SystemMessagePromptTemplate.from_template(template)

    human_template="Transcript:{text} " # Simply just pass the text as a human message
    human_message_prompt_map = HumanMessagePromptTemplate.from_template(human_template)

    chat_prompt_combine = ChatPromptTemplate.from_messages(messages=[system_message_prompt_map, human_message_prompt_map])
    chain = load_summarize_chain(llm=llm,
                                 chain_type="map_reduce",
                                 combine_prompt=chat_prompt_combine,
                                  verbose=True,

                                )

    summarizetext = chain.run(docs)
    return summarizetext,





    # print("adding vectordb ------------------>")
    # adding_data_to_vectordb(summarizetext)


    # schema = {
    #     "properties": {
    #         "topic": {"type": "string"},
    #         "description": {"type": "string"}},
    # }
    # chain1 = create_extraction_chain(schema, llm3)
    # final_resp=chain1.run(topics_found)
    #




def find_topics(text):
    from langchain.chains import create_extraction_chain, create_extraction_chain_pydantic
    llm3 = ChatOpenAI(temperature=0.3,
                      openai_api_key=os.getenv('OPENAI_API_KEY', "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"),
                      model_name="gpt-3.5-turbo-0613",
                      request_timeout=180
                      )

    topics_text=text
    text_splitter1 = RecursiveCharacterTextSplitter(separators=["\n\n", "\n", " "], chunk_size=10000, chunk_overlap=2200)
    docs1 = text_splitter1.create_documents([topics_text])
    print(docs1)

    template1 = f"""
       find the most relevant  and suitable one line defined topic from the given text  .
      """
    system_message_prompt_map1 = SystemMessagePromptTemplate.from_template(template1)

    human_template1 = "Transcript: {text}"  # Simply just pass the text as a human message
    human_message_prompt_map1 = HumanMessagePromptTemplate.from_template(human_template1)

    chat_prompt_combine1 = ChatPromptTemplate.from_messages(
        messages=[system_message_prompt_map1, human_message_prompt_map1])
    chain1 = load_summarize_chain(llm3,
                                 chain_type="map_reduce",
                                 combine_prompt=chat_prompt_combine1,
                                 verbose=True
                                 )

    topics= chain1.run({"input_documents":docs1 })
    return topics






